### PR TITLE
Add horizontal iPad margins

### PR DESCRIPTION
**Pull request by rsanchezsaez**
Deals with [issue #77](https://github.com/ResearchKit/ResearchKit/issues/77).

I'll continue working on [issue #76](https://github.com/ResearchKit/ResearchKit/issues/76) after this is reviewed and merged.

### CODE REVIEW

**Comment by rsanchezsaez** [comment]
I re-did the iPad margins calculations because I noticed some problems (see commit message for details). I feel this version is much more robust.

I performed exhaustive testing on *iPad Air* and *iPhone 6*: all *ORKCatalog* items seem to work as expected on both devices.

**Comment by jwe-apple** [comment]
Ok, code looks good. I'll do some testing tomorrow; I'm mainly concerned about iPhone regressions this might introduce.
Please could you merge your whitespace changes, which conflict?

**Comment by jwe-apple** [comment]
Ok - no regressions spotted on iPhone.

The bottom separator is being dropped on some forms:
img_0001 1

The scroll indicator should be fully to the right side of the screen, having double checked against the behavior during setup of a new iPad. This might be tricky! Example of the problem:
img_0004 1

**Comment by rsanchezsaez** [comment]
Will check these issues.

Could you provide an iPad setup screenshot with a visible scroll indicator for reference? Thanks.

**Comment by jwe-apple** [comment]
Yep.

img_0002 2

**Comment by rsanchezsaez** [comment]
Thanks.

**Comment by rsanchezsaez** [comment]
Both Issues fixed. Also resolved conflicts with new whitespace code.

Please note that I also changed the default view/table margin on *iPhone 6* screen and lower from *16* to *15*. Note the comment on the last line of this function (which went away with the iPad margin implementation):

    CGFloat ORKTableViewLeftMargin(UITableView *tableView){
        if (ORKWantsWideContentMargins(tableView.window.screen)) {
            if (CGRectGetWidth(tableView.frame) > 320.0) {
                return ORK_LAYOUT_MARGIN_WIDTH_THIN_BEZEL_REGULAR;
            }
            else {
                return ORK_LAYOUT_MARGIN_WIDTH_THIN_BEZEL_COMPACT;
            }
        }
        else {
            // Probably should be ORK_LAYOUT_MARGIN_WIDTH_REGULAR_BEZEL
            return ORK_LAYOUT_MARGIN_WIDTH_THIN_BEZEL_COMPACT;
        }
    }

It turns out the comment was right: I measured the table separator insets on the Settings app and it was *15* indeed.

**Comment by rsanchezsaez** [comment]
I tested the scroll indicators both in the `ORKTableContainerView` (*ORKTest* long kitchen-sing form) and in the `ORKVerticalContainerView` (I tested a very long text field question which caused scrolling on my private test). They seem fine both on *iPad Air* and *iPhone 6*.

**Comment by rsanchezsaez** [comment]
Fixed. :)

**Comment by rsanchezsaez** [comment]
Float comparison fixed.

**Comment by jwe-apple** [comment]
Tests pass.
Ricardo - could you merge this one up to date for me? Thanks!

**Comment by rsanchezsaez** [comment]
Sure thing, *master* merged.

**Pull request merged**
