### PR TITLE
Add support for Travis builds

### PR DESCRIPTION
**Pull request by pietbrauer**
This turns on automated builds but is sadly depending on https://github.com/travis-ci/travis-ci/issues/3216

Current build status: [Build Status](https://travis-ci.org/pietbrauer/ResearchKit)

### CODE REVIEW

**Comment by modocache** [comment]
+1, would love to see continuous integration results surfaced on pull requests!

Alternatively, if the maintainers of this project are using Xcode bots to perform continuous integration, would you all consider making a public web page displaying the build status?

**Comment by ohwutup** [comment]
:+1: to @modocache and Xcode bots

**Comment by jwe-apple** [comment]
Happy to have it build on Travis when they're up to date. But the configuration should also:
1) build the ORKTest app and run its tests
2) do a sanity build of the ORKCatalog Swift sample

**Comment by pietbrauer** [comment]
I added test execution for both sample apps as well. @modocache could you have a look as well? :dancers:

**Comment by jwe-apple** [comment]
@pietbrauer Looks good to me. Let's keep this pull request open pending Travis being ready.

**Comment by pietbrauer** [comment]
Hey @jwe-apple this PR is finally green. Is this still relevant as I saw you guys moved to another, most likely private, CI?

**Comment by jwe-apple** [comment]
Ah, thanks for doing this. This is still relevant - we have private CI which I need to use internally, but having a public one is altogether better for our contributors. I'll have a look as soon as I get a chance.

**Comment by tapwork** [comment]
+1

**Comment by jwe-apple** [comment]
Locking this issue. Yes, we want to do this in principle, but staying backward compatible with whatever Travis's most recent supported version of Xcode is may not be practical.

**Pull request closed without merging**
