### PR TITLE
Fix for hidePredicate changes where an ORKTableSection may contain more than one ORKFormItem

### LINKED ISSUE #1278: ORKCatalog Form Survey Example Crash
Steps to reproduce:
1) Build the ORKCatalog target
2) Select "Form Survey Example"
It crashes in [ORKFormStepViewController hideSections].

The code makes the incorrect assumption there's a one-one correspondence between formItems and _allSections.
I would think there should be some logic that a section is only hidden if all of it's items are hidden.

### PR DESCRIPTION
**Pull request by eschramm**
Fixes #1278. While adding complexity to allow animation for showing and hiding that may occur as items on the form change, this properly handles `ORKTableSection`s that may contain more than one `ORKFormItem`. It also maintains the flexibility to hide form items that could be in the same section by hiding or showing the rows in addition to the section for the tableview. My apologies for the miss on initial implementation.

### CODE REVIEW

**Comment by ninoguba** [comment]
@akshay-yadav-apple I know it's WWDC week so you guys must be busy, but hope you or @srinathtm-apple can merge this PR when you guys get the chance to review.  thanks!

**Comment by srinathtm-apple** [comment]
@ninoguba - yup, we will look into this soon!

**Comment by srinathtm-apple** [comment]
Hey @eschramm - quick heads up, we had to revert your original PR for our current release, but let's revisit your feature in the coming weeks to get it integrated back in!

**Comment by srinathtm-apple** [comment]
@eschramm - merging into master, thank you!

**Pull request merged**
