### PR TITLE
Add code coverage support via Travis/Coveralls

### PR DESCRIPTION
**Pull request by lazerwalker**
This turns on automated code coverage reports via [Slather](https://github.com/venmo/slather) and [Coveralls.io](https://coveralls.io).

Since this workflow relies on CI to generate reports, this is currently blocked by (and was forked from) https://github.com/ResearchKit/ResearchKit/pull/14.

### CODE REVIEW

**Comment by pietbrauer** [comment]
@jwe-apple @YuanZhu-apple I think this and #14 (mine) are obsolete and can be closed.

**Comment by kelseydedoshka-apple** [comment]
@lazerwalker thanks for the contribution, but it looks like things are blocked on this issue. We agree with @pietbrauer - are there any action items you would like us to take here or should we close this?

**Comment by divyanag** [comment]
@lazerwalker just following up on this, we're planning on closing this issue at the end of the week unless there's anything you'd like us to look into here. Thanks again for your contribution!!

**Comment by lazerwalker** [comment]
Nope, close it on down! Thanks for the follow-up!

**Comment by kelseydedoshka-apple** [comment]
@lazerwalker - thanks for the contribution and quick reply! Closing down this PR.

**Pull request closed without merging**
