### PR TITLE
Reorganize 'ORKCatalog' into subsections

### PR DESCRIPTION
**Pull request by rsanchezsaez**
Since `ORKCatalog` is also growing, I have reorganized it into alphabetically-sorted sections mirroring the [project's readme](https://github.com/ResearchKit/ResearchKit/blob/master/README.md) structure.

Let me know what you think.

### CODE REVIEW

**Comment by YuanZhu-apple** [comment]
Overall it is very good.

Is the alignment difference on purpose?
screen shot 2015-09-01 at 4 26 13 pm

**Comment by rsanchezsaez** [comment]
Yes, to differentiate between the *container survey/form examples*, and the
*individual question examples* which can be used in either one (except
*image capture*, which is survey-only, I think).

**Comment by YuanZhu-apple** [comment]
Not quite like alignment difference.
For the questions, maybe better to create a separate section for them? What do you think?

**Comment by rsanchezsaez** [comment]
Yeah, I was not completely convinced either. I've added new commit moving the *Survey Questions* to a new section.

**Comment by YuanZhu-apple** [comment]
r=me.

**Comment by YuanZhu-apple** [comment]
@rsanchezsaez Can you get a chance to update this PR? So I can merge it.

**Comment by rsanchezsaez** [comment]
@YuanZhu-apple: Did you mean reorganizing the files as I just did in `ORKTest`? I just added commits doing that.

Also, I noticed that additional localization languages are not added in `ORKCatalog` so all tasks show in English. Should we add as they are in `ORKTest`?

**Comment by YuanZhu-apple** [comment]
Sorry, I meant making this PR mergeable.

**Comment by YuanZhu-apple** [comment]
Or you want do `files reorganizing` in this PR as well?

**Comment by rsanchezsaez** [comment]
Ah, I see. Ok, I'll merge this with master, plus the *files reorganization*.

Let me fix something first: I'm going to remove the `samples` to `Samples` folder rename commit, as it messes with *Xcode* history when using the *Version Editor*, so it's not worth it.

**Comment by rsanchezsaez** [comment]
Ok:
- Merged `master`.
- Reorganized project files.
- Updated `ResultTableProvides` to match `TaskListRow`.
- Updated `readme.md` to add formatting and information about sections.

**Comment by YuanZhu-apple** [comment]
r=me.

**Pull request merged**
