### PR TITLE
Indicate that consent document must be copied for signature to be applied correctly

### PR DESCRIPTION
**Pull request by getaaron**
Closes https://github.com/ResearchKit/ResearchKit/issues/120.

### CODE REVIEW

**Comment by getaaron** [comment]
@jwe-apple Then #120 should be reopened as a bug. The exact same code failed to show the signature in the PDF until I copied it.

**Comment by jwe-apple** [comment]
Interesting. Looking at the code of -applyToDocument: there's no reason it should fail. If you have a working test case, could you zip it up and email to me? Thanks!

**Comment by jwe-apple** [comment]
Or alternatively point me to a github repo with the broken sample.

**Comment by getaaron** [comment]
@jwe-apple https://github.com/getaaron/zombie demonstrates the behavior.

Specifically, see `generatePDFData()`:

image

Currently, the user's signature won't appear on the PDF.

If you uncomment this line:

    // let document = consentDocument.copy() as! ORKConsentDocument // This works

and change both instances of `consentDocument` in that method to `document`, then it *will* work.

**Comment by getaaron** [comment]
Oh, sorry. My fault. I didn't realize that the `private var consentDocument: ORKConsentDocument { … }` I copied from the sample project doesn't retain the consent document between calls. My original code doesn't work because it applies the signature result to one document, and then generates the PDF from a brand new document.

**Comment by jwe-apple** [comment]
Ah, awesome. Thanks for chasing this down!

**Comment by skoth001** [comment]
I can't seem to access consentDocument that I created in a different file in my ViewController page? How exactly would you do that?

**Comment by YuanZhu-apple** [comment]
@skoth001 Can you share us a piece of code snippet to explain your confusion?

**Comment by skoth001** [comment]
So this is the code that creates the consent task

var steps = [ORKStep]()
    
    var consentDocument = ConsentDocument
    let visualConsentStep = ORKVisualConsentStep(identifier: "VisualConsentStep", document: consentDocument)
    steps += [visualConsentStep]
    
    let signature = consentDocument.signatures!.first as! ORKConsentSignature
    
    let reviewConsentStep = ORKConsentReviewStep(identifier: "ConsentReviewStep", signature: signature, inDocument: consentDocument)
    reviewConsentStep.text = "Review Consent"
    reviewConsentStep.reasonForConsent = "Consent to join the study"
    steps += [reviewConsentStep]
    
    
    return ORKOrderedTask(identifier: "ConsentTask", steps: steps)

This code is in its own file called ConsentTask

In my view controller, which is where I call the consent task itself, inside the taskViewController function in the reason completed, I am not able to access the consentDocument I created

**Comment by YuanZhu-apple** [comment]
@skoth001 You should be able to get the `visualConsentStep` from `taskViewController.task`, and `consentDocument` is right on  `visualConsentStep`

Something like:
```
visualConsentStep = [taskViewController.task stepWithIdentifier:"VisualConsentStep"];
consentDocument = visualConsentStep.consentDocument;
```

**Comment by skoth001** [comment]
I am getting an error when I try 

let visualConsentStep = taskViewController.task.stepWithIdentifier("VisualConsentStep") 

Sorry I am new to swift, this may be very easy 

Error: Value of optional type ((String -> ORKStep?)?) not unwrapped

**Comment by skoth001** [comment]
When I try to do 

consentDocument = visualConsentStep.consentDocument it gives me 

type of expression is ambiguous without more context, any advice on how to fix this

**Comment by YuanZhu-apple** [comment]
Did you do a cast to `ORKVisualConsentStep` ?

**Comment by skoth001** [comment]
var document = visualConsentStep as ORKVisualConsentStep.consentDocument

I tried this but it says consentDocument is not a member of ORKVisualConsentStep

**Comment by YuanZhu-apple** [comment]
I am pretty sure it is there:
```
@interface ORKVisualConsentStep : ORKStep

/**
 Returns an initialized visual consent step using the specified identifier and consent document.
 
 @param identifier          The identifier of the visual consent step, unique within the document.
 @param consentDocument     The informed consent document.
 */
- (instancetype)initWithIdentifier:(NSString *)identifier document:(nullable ORKConsentDocument *)consentDocument;

/**
 The consent document whose sections determine the order and appearance of scenes
 in the visual consent step.
 */
@property (nonatomic, strong, nullable) ORKConsentDocument *consentDocument;

@end
```

**Comment by skoth001** [comment]
I got it working thank you for the help

**Pull request merged**
