### PR TITLE
Add "ORKWebViewStep"

### PR DESCRIPTION
**Pull request by chrisnowak**
This adds a simple ORKWebView step which allows you to embed a WKWebView in a task, using either a url or embedded html.  The embedded html can pass results back to the native ResearchKit code using Javascript.

## Background
While full native implementations of steps are in most cases preferable (and the only option in some cases to be able to leverage things like HealthKit) - we have encountered a few use cases where the ability to embed a WebView in a step really could be useful:
1.  Research instruments which either are too specific to a particular application to warrant a first-class native implementation (and contribution to ResearchKit), or they are still in the prototyping stages so a full native implementation would be premature (but there's still desire to try them out)
2.  We have had requests for the ability to embed highly custom content - which would be satisfied if we could just embed a webview
3.  Using a webview also allows for these instruments to be used in cross platform - the same (or similar) code for a step/instrument could be leveraged for Android or Web based surveys

For instance - here's a body site map developed as HTML/CSS/Javascript, embedded in a ResearchKit survey:

screen shot 2017-11-14 at 10 03 12 am

Everything below the "Step 1 of 3" is HTML/CSS/Javascript.  

## Implementation

I attempted to keep this as simple as possible - but would very much be open to feedback / ideas for improvement.  

Currently the WebViewStep can take either embedded HTML or an external url.  The WebView itself is set up using a WKUserContentController / script message hander to respond to "ResearchKit" messages from javascript.  In order for the user to proceed, this line of javascript must be executed:
```
window.webkit.messageHandlers.ResearchKit.postMessage(answer);  //answer is the string result of the step
```

There is currently no support for restoring answers - so if the user goes back to the step, they will have to fill it out again before proceeding.  It might be possible to accomplish restoring answers by establishing that there must be a javascript function called "restoreAnswers(string)" or something - and once the webview loads we could call that function natively with the answer they had previously supplied.  I opted to leave that for the future, but could look into it further if necessary.

Could be a solution for the folks who proposed:
https://github.com/ResearchKit/ResearchKit/issues/767
https://github.com/ResearchKit/ResearchKit/issues/367

It could also be interesting in the future if an interstitial webview step with javascript could be used to accomplish: https://github.com/ResearchKit/ResearchKit/issues/873 - by passing the current survey results to the embedded view, which could evaluate a "score" via javascript.  (Though again - not possible from this PR - would require the code to pass the results to the webview).

As part of this PR I added this to both ORKTest and ORKCatalog, with a simple embedded html example.

### CODE REVIEW

**Comment by kelseydedoshka-apple** [comment]
@chrisnowak - this is a great idea. I think having the ability to add custom content via HTML/CSS/JavaScript would be really beneficial to a lot of developers. I would love to chat a bit further with you about the URL approach however.

I have some high level concerns about allowing developers to point their apps to a URL as the content contained in the URL can be dynamic and unfortunately means that it could be manipulated post app creation/consent/etc. In theory this might allow developers to abuse the system. I am curious your thoughts on this? On the flip side, I think the html approach is fantastic as it is static and will be baked into the application.

**Comment by chrisnowak** [comment]
@kelseydedoshka-apple Thanks for taking a look! I'm glad this resonates.

Could you expand on the situation you are imagining occurring - how do you imagine a developer might abuse the system?   I had pondered that for a while but I couldn't actually see a (plausible) scenario by which it could be "abused"...many, many, apps out there use embedded WebViews to render content.  

While having the externalized content definitely introduces another moving part - that's also part of what makes this powerful.  A great example could be patient education resources - one could introduce a highly dynamic step which incorporates access to entire databases of educational materials, without having to actually have that content packaged with the app (meaning - no app store release needed to update that content).  

Absolutely agree that (when possible) the embedded html approach is preferable - as it doesn't require an internet connection and it is nice to have the survey be entirely self-contained.  However - we see (and have encountered) some profound use cases where that might not be possible...

**Comment by kelseydedoshka-apple** [comment]
@chrisnowak - thanks for the additional information and the use cases you described help provide some additional understanding!

To try and clarify my concern a little bit more (and the case of this happening is very slim, but unfortunately still plausible). A developer could initially use a web view to display informational or educational content like you mentioned above (which I think is a great use case by the way), to then later change that URL to display something like advertisements or irrelevant content, which can lead to a poor user experience or even user misrtust. It is more of a precautionary concern, similar to how the App Store Review requires a higher age rating if you have a view that can display anything from the web (as we have no way to determine or screen what that content may be). Let me know if the helped clarify at all, and as we discuss this I am going to get some additional opinions on this as well as I could be over thinking it here.

As I mentioned before I am a big fan of this idea and would love to see it as a part of the framework, I just want to make sure all use cases are considered. Would you be interested in contributing this step with just the HTML property and not the URL?

**Comment by chrisnowak** [comment]
@kelseydedoshka-apple sure - if the externalurl will hold this up, I am ok with refactoring to just have it support the embeddedhtml property.  I will go ahead and make that change and fix the current conflicts with master as well.

**Comment by kelseydedoshka-apple** [comment]
@chrisnowak - great, I appreciate your flexibility here and looking forward to seeing the refactor so we can get this into the framework!

**Comment by chrisnowak** [comment]
@kelseydedoshka-apple no problem - I have updated the code to remove the url property on WebViewStep, and fixed the conflicts with master.  Thanks!

**Comment by kelseydedoshka-apple** [comment]
@chrisnowak - thanks for getting this updated so quickly. Great contribution!

**Pull request merged**
