### PR TITLE
Coding Style Guide: add 'Nullability Annotations' section

### PR DESCRIPTION
**Pull request by rsanchezsaez**
Add *"Nullability Annotations"* section to the *Coding Style Guide*.

Also:
- Make new separate section for *Header File Example*.
- Other very small fixes.

### CODE REVIEW

**Comment by YuanZhu-apple** [comment]
Thanks, glad we can add 'Nullability Annotations' section!

**Comment by YuanZhu-apple** [comment]
Since I have merged iOS9 branch to master. In Xcode 7, Objective-C started to support `Generics`, can you add section for it? 
https://developer.apple.com/library/prerelease/ios/documentation/DeveloperTools/Conceptual/WhatsNewXcode/Articles/xcode_7_0.html#//apple_ref/doc/uid/TP40015242-SW3

**Comment by rsanchezsaez** [comment]
Sure thing, I'll add the *Generics* section soon.

**Comment by umerkhan-apple** [comment]
r=m3

**Comment by rsanchezsaez** [comment]
Added *"Lightweight Generics"* section, plus some additional small improvements.

**Comment by YuanZhu-apple** [comment]
r=me. Thanks @rsanchezsaez !

**Pull request merged**
