### PR TITLE
Fix documentation issue

### PR DESCRIPTION
**Pull request by Ajinkya213**
Updated the docs for consistency in markdown files.

### CODE REVIEW

**Comment by Ajinkya213** [comment]
Hello @louie-apple,

Could you please take a look at my pull request and merge it the 'main' branch. This is a basic document fix. 
If you have any questions please let me know.

Have a great day.

**Review by Ajinkya213 — COMMENTED** [review]
Can you please mark where I made mistake?

**Comment by Pariecemckinney-apple** [comment]
Hello @Ajinkya213, 

Thank you submitting this PR! There was no mistake on your end in terms of the changes you’ve proposed. However, with our 3.0 release we’ve began moving our documentation to DocC (https://github.com/ResearchKit/ResearchKit/tree/main/ResearchKit/ResearchKit.docc) as opposed to the documents targeted in this PR.

With that in mind, our DocC documentation will likely be updated frequently as the framework continues to move forward. So if you look there and find anything that should be updated or added we'll make sure it's reviewed as quickly as possible. We appreciate you taking the time to contribute and it has not gone unnoticed!

**Comment by Ajinkya213** [comment]
> Hello @Ajinkya213,
> 
> Thank you submitting this PR! There was no mistake on your end in terms of the changes you’ve proposed. However, with our 3.0 release we’ve began moving our documentation to DocC (https://github.com/ResearchKit/ResearchKit/tree/main/ResearchKit/ResearchKit.docc) as opposed to the documents targeted in this PR.
> 
> With that in mind, our DocC documentation will likely be updated frequently as the framework continues to move forward. So if you look there and find anything that should be updated or added we'll make sure it's reviewed as quickly as possible. We appreciate you taking the time to contribute and it has not gone unnoticed!

Thank you so much for noticing me ❤️ @Pariecemckinney-apple and the Apple team. 

First of all the people from apple-team and contributors behind the ResearchKit, CareKit and HealthKit are totally awesome for creating this epic open-source frameworks. These frameworks are positively impacting the lives from doctors, patients healthcare workers etc.

I have some questions for ResearchKit DocC but I can create a new issue for 3.0 release which makes more sense.

Finally I am closing this pull request with lots of love and support to all the devs who are involved in this project.

**Pull request closed without merging**
