### PR TITLE
Center pickers on iPad

### PR DESCRIPTION
**Pull request by rsanchezsaez**
Fixes [issue #75](https://github.com/ResearchKit/ResearchKit/issues/75).

### CODE REVIEW

**Comment by rsanchezsaez** [comment]
I think you are right regarding duplicate constraints. If that's the case, there are other *ResearchKit* classes potentially doing `updateConstraints:` wrong that should be fixed: `ORKActiveStepTimerView`, `ORKScaleSliderView`, `ORKSurveyAnswerCellForNumber`, `ORKSurveyAnswerCellForScale`, `ORKSurveyAnswerCellForTextField`, `ORKTextFieldView`.

Tell me if this is a problem and I'll create and issue.

For the rest of the classes that implement `updateConstraints:`, there are what seem two equivalent methods for removing all current constraints.

Some use `removeConstraints:`:
- `ORKActiveStepQuantityView`, `ORKQuantityPairView`, `ORKFitnessContentView`, `ORKSurveyAnswerCellForText`, `ORKWalkingContentView`.

Other use `deactivateConstraints:` and then *nil* the `_constants` ivar:
- `ORKAudioContentView`, `ORKConsentSignatureWrapperView`, `ORKTableContainerView`, `ORKTappingContentView`, `ORKNavigationContainerView`, `ORKSpatialSpanMemoryContentView`, `ORKVerticalContainerView`.

Which of these two is the preferred method?

Yet, there are some classes that use *ivars* to track and handle the constraints manually added: `ORKFormItemTextFieldBasedCell`, `ORKStepHeaderView`, `ORKContinueButton`. Not sure if these views cannot just remove and re-add all constraints (which I think would be coherent, simpler and more maintainable) due to having some constraints being added elsewhere.

**Comment by rsanchezsaez** [comment]
For what it's worth, the `updateConstraints:` documentation states:

> You must not invalidate any constraints as part of your constraint update phase. You also must not invoke a layout or drawing phase as part of constraint updating.

Does *invalidate* means *deactivate*? That makes me wonder about the `deactivateConstraints:` way.

Also:

> *IMPORTANT*
> Call [super updateConstraints] as the final step in your implementation.

And several `updateConstraints:` implementations do this wrong by calling it before anything else.

**Comment by rsanchezsaez** [comment]
I fixed this in what I felt was the most sensible way. Looking forward to your comments on the issues I mentioned.

**Comment by jwe-apple** [comment]
Your fix works for me.

**Pull request merged**
