### PR TITLE
[Misc] Code homogenization

### PR DESCRIPTION
**Pull request by rsanchezsaez**
This PR does a minor `ORKHelpers.h`/`ORKDefines.h`/`ORKDefines_Private.h` reorganization, and adds some minor and fairly harmless coding style conforming and homogenization (whitespace around unary and ternary operators; usage of some predefined macros; avoid using the `__` prefix, [Issue #510](https://github.com/ResearchKit/ResearchKit/issues/510)).

Things of note:
- `ORKDefines.h` was split into `ORKDefines.h` and `ORKTypes.h`, which favours encapsulation and reduces inter-dependencies.
- `ORKDefines_Private.h` (containing some functions needed in `ORKTest` unit tests) was renamed to `ORKHelpers_Private.h`, since those are helper functions rather than macros. At the same time, the localization function and macro declarations were moved to `ORKHelpers.h` (which has internal visibility), since the localization functions are not needed outside *ResearchKit*.

See the commit messages for details on the the rest of minor changes.

### CODE REVIEW

**Comment by YuanZhu-apple** [comment]
@rsanchezsaez I saw make some style changes are not mentioned in `code style guide`, do you mind updating `code style guide` as well?

**Comment by rsanchezsaez** [comment]
> some style changes are not mentioned in code style guide, do you mind updating code style guide as well?

I have added some new details to the *Coding Style Guide*. Please let me know if anything else is missing.

I also took the chance to do some additional code-base improvements and standardization for issues that I just found around.

**Comment by YuanZhu-apple** [comment]
@rsanchezsaez Thanks for this patch! Does this patch have any dependency? 

Do you mind resolving the conflict and I can get this merged?

**Comment by rsanchezsaez** [comment]
Nope, the opposite, [PR#648](https://github.com/ResearchKit/ResearchKit/pull/648) depends on this. I'll resolve merge conflicts for both soon.

**Comment by rsanchezsaez** [comment]
@YuanZhu-apple Merge conflicts resolved. I'll resolve the ones on [PR #648](https://github.com/ResearchKit/ResearchKit/pull/648) after you merge this one.

**Comment by YuanZhu-apple** [comment]
@rsanchezsaez It has conflicts again:|

**Comment by rsanchezsaez** [comment]
Conflicts fixed!

**Comment by YuanZhu-apple** [comment]
r=me.

**Pull request merged**
