### PR TITLE
ORKQuestionResult could get truncated Chinese texts

### PR DESCRIPTION
**Pull request by weijentu**
Hi there,
I found a small issue that ``ORKQuestionResult`` could get truncated Chinese texts before
``textFieldDidEndEditing`` is called in ``UITextFieldDelegate`` once the property ``multipleLines`` of ``ORKTextAnswerFormat`` is set to ``false``.

The repository “truncated-branch”: https://github.com/weijentu/ResearchKit/tree/truncated-branch
which is revised to be able to demonstrate the scenario right away. Also uncomment line 202 in ``ORKSurveyAnswerCellForText`` can address the issue.

There are also two videos to elaborate truncated Chinese texts and the difference between before and after.

**Before:**
https://db.tt/jHlCyr62
#Notice that the last character is always truncated before ``textFieldDidEndEditing`` is called in ``UITextFieldDelegate``.

**After:**
https://db.tt/jeh1O20k

Cheers,

Allen

### CODE REVIEW

**Comment by umerkhan-apple** [comment]
@weijentu Good catch! r=m3.

**Comment by YuanZhu-apple** [comment]
@weijentu I am having trouble repro this, see this https://db.tt/DFI5Dz2p

**Comment by weijentu** [comment]
@YuanZhu-apple Did you set ``multipleLines = false`` in your test? 
Ex.
<code>let texAnswerFormat = ORKAnswerFormat.textAnswerFormatWithMaximumLength(64)
textAnswerFormat.multipleLines = `false
</code>

The size of text area in your video looks quite big. The issue happens once the text area is ``UITextField``. For ``UITextView``, Chinese texts will not be truncated.

**Comment by weijentu** [comment]
@YuanZhu-apple  By the way, I just tried to record a video of how I reproduce the issue. It might be easier to explain what I mean. [https://db.tt/j7ypk3u5](https://db.tt/j7ypk3u5) 

Cheers :-)

**Comment by YuanZhu-apple** [comment]
r=me.

**Pull request merged**
