### PR TITLE
Split ORKResult code files into separate files.

### PR DESCRIPTION
**Pull request by syoung-smallwisdom**
This addresses https://github.com/ResearchKit/ResearchKit/issues/957.

`ORKResult` is getting huge, difficult to maintain, and difficult to handle merge conflicts. I’ve separated out all the active task results into a file for each module result type. Additionally, I split out the `ORKQuestionResult` subclasses into a separate file and the `ORKCollectionResult` subclasses into a separate file. Finally, the remaining result subclasses were put into a separate file in the same group as their associated step.  This is almost entirely a copy/paste operation. The only changes I have made are as follows:

1. Removed unused `ORKDataResult` which was a privately defined subclass and therefore inaccessible externally.
2. Fixed `ORKHolePegTestResult` decoding of the samples.
3. Fixed a warning about the `ORKLocation` using a nil value in it's initializer.

### CODE REVIEW

**Comment by umerkhan-apple** [comment]
@syoung-smallwisdom Thanks for this great refactor! Will definitely have the team test it out since it is quite a large code refactor. 

Very much appreciate the fix (3) listed above! Bothered me every time I compiled. 👍

**Comment by syoung-smallwisdom** [comment]
@Pariecemckinney-apple Ping

**Comment by rsanchezsaez** [comment]
@Pariecemckinney-apple @kelseydedoshka-apple It'd be good to review and merge this too. ;-)

**Comment by syoung-smallwisdom** [comment]
@Pariecemckinney-apple @kelseydedoshka-apple
Ping.
I've resolved the conflict with master by adding the change by @akshay-yadav-apple to `ORKToneAudiometryResult`.

**Comment by kelseydedoshka-apple** [comment]
@syoung-smallwisdom - thanks for the update. @Pariecemckinney-apple please take a look at this.

**Comment by Pariecemckinney-apple** [comment]
@syoung-smallwisdom Everything looks great but there are result files missing for the "ORKWebViewStep" which is a step that was added recently (within the last couple of weeks). Would you mind adding the result class for this last step? 

After that, we can move forward with merging. Really looking forward to this refactor!

**Comment by syoung-smallwisdom** [comment]
@Pariecemckinney-apple 

I have added the missing class. Additionally, I ran the `ORKTest` unit tests and fixed a number of issues that your team mistakenly pulled into master. Please merge this soon before accepting more code.

**Comment by Pariecemckinney-apple** [comment]
Great! Merging now.

**Pull request merged**
