### PR TITLE
Fixed formatting of curly braces in all files

### PR DESCRIPTION
**Pull request by codestergit**
I have fixed the formatting of braces in all files to maintain consistency in whole project . Please let me know if anything need to update. This is related with issue  https://github.com/ResearchKit/ResearchKit/issues/24
Thanks

### CODE REVIEW

**Comment by rismay** [comment]
LGTM.

**Comment by wczekalski** [comment]
Introduces too much noise to the history IMO. Maybe we could add some style-checking to [travis](https://github.com/ResearchKit/ResearchKit/pull/14). 

I don't have too much experience with linters though.

**Comment by codestergit** [comment]
Resolved the conflicts. Now this can be merged. Please let me know your views.
Thanks

**Comment by johnstourt** [comment]
looks good to me :+1:

**Comment by jwe-apple** [comment]
@wczekalski We are considering accepting this now, because it's early enough in the history.

We also looked at doing clang-format across the whole codebase but it's not accurate enough on Objective-C.

**Comment by rsanchezsaez** [comment]
We need `clang-format-objc`. ;)

**Comment by stormpeter** [comment]
Yes I have also used `clang-format-objc` but it not well satisfied with the need.

**Comment by jwe-apple** [comment]
Chose to bring this up to date and merge. No real harm in it at this stage in the project.

**Comment by rsanchezsaez** [comment]
Excellent. Visual consistency for great justice.

**Comment by rismay** [comment]
:+1:

**Comment by jwe-apple** [comment]
Oh no, not the thumbs again!

**Comment by rismay** [comment]
Better?

**Comment by codestergit** [comment]
Thanks for merging this @jwe-apple

**Pull request merged**
