### PR TITLE
Split out ORKOrderedTask task modules into a separate file.

### PR DESCRIPTION
**Pull request by syoung-smallwisdom**
Adding active task modules to ResearchKit or making changes to `ORKOrderedTask` is complicated by having the a single file for both. Additionally, it complicates an effort that Sage is doing to include support for watchOS (and eventually tvOS and macOS).

This PR does the following:

1. Split the predefined active tasks into a separate file while retaining the git blame history.
2. Move all the enums to `ORKTypes` to consolidate where they are defined.
3. Consolidate the active tasks into a single file by moving the Hole Peg Test code.

### CODE REVIEW

**Comment by umerkhan-apple** [comment]
@syoung-smallwisdom Great refactoring! Completely agree with this approach. Will have the team test it out to make sure everything remained in-tact in the process of refactoring. Thanks for this PR! 👍

**Comment by syoung-smallwisdom** [comment]
@Pariecemckinney-apple Ping

**Comment by rsanchezsaez** [comment]
@Pariecemckinney-apple @kelseydedoshka-apple It'd be good to review and merge this too. ;-)

**Comment by kelseydedoshka-apple** [comment]
Looks great. @Pariecemckinney-apple, @akshay-yadav-apple - please take a look as well to confirm everything remained in tact before merging.

**Pull request merged**
