### PR TITLE
Fixed compilation when OpenGLES is unavailable

### PR DESCRIPTION
**Pull request by Brett-Best**

### CODE REVIEW

**Comment by louie-apple** [comment]
Thank you for submitting your PR. We are curious in what cases do you see that `OpenGLES is unavailable` ?

**Comment by Brett-Best** [comment]
When compiling for macOS (Catalyst)
> OpenGLES is deprecated and is not available when building for Mac Catalyst.

**Comment by louie-apple** [comment]
Thanks for the clarification.  Since this PR is only partially addressing catalyst support, we can't merge at this time.
Have you done the work to fully support macOS (Catalyst)?

**Comment by Brett-Best** [comment]
I guess in principle this PR doesn’t claim to add Catalyst support, e.g. if/when iOS removes OpenGLES then ResearchKit would still compile. I might be wrong, but it seemed like the usage of OpenGLES was for a “deprecated” component of ResearchKit that was replaced with a newer component?

Nonetheless, the portion of RK that I tested out so far in Catalyst was the surveys which seemed to work well after applying the fix linked to in this comment https://github.com/ResearchKit/ResearchKit/issues/1509#issuecomment-1242568509

**Comment by louie-apple** [comment]
Thank you for sharing. You're correct: The OpengGLES components in ResearchKit have been deprecated which means they'll be removed in a future release.

**Comment by louie-apple** [comment]
Glad to hear that you are able to compile for Mac Catalyst now. You are correct that `ORKEAGLMoviePlayerView.h/m`  was still left in the codebase even though the class is deprecated. Those files will be removed in a future release.

**Pull request closed without merging**
