### PR TITLE
CorrectDestionation

### PR DESCRIPTION
**Pull request by md0u80c9**
Changed all instances of Destionation to Destination

### CODE REVIEW

**Comment by rsanchezsaez** [comment]
Thanks Andrew. Fix looks good!

**Comment by YuanZhu-apple** [comment]
Hey @md0u80c9 can you resubmit this PR against `convergence` branch? 
So this fix can be included in next release. Thanks!

**Comment by md0u80c9** [comment]
Is there a way to do this from GitHub or Xcode without re-doing it?

**Comment by YuanZhu-apple** [comment]
Can you create a new PR and select against `convergence`?

**Comment by md0u80c9** [comment]
I've just checked the convergence branch - the change is on code which is only on the Master branch at present, so I think the PR only needs to apply to master.

**Comment by YuanZhu-apple** [comment]
OK, I will accept it and cherry pick it to `convergence`.

**Pull request merged**
