### PR TITLE
Update extension to `ORKPredicateStepNavigationRule` to support Swift 3 and 2.x

### PR DESCRIPTION
**Pull request by king7532**
See [issue 714](https://github.com/ResearchKit/ResearchKit/issues/714)

### CODE REVIEW

**Comment by YuanZhu-apple** [comment]
@king7532 It was nice to meet you at dub dub:)

I just pushed a branch based on `stable` => `stable_xcode80_candidate`, if you plan to work on an app with XCode 8.0 beta, I suggest you using the new branch.

 But I think there is no hurt to add this version check in the master branch.

**Comment by YuanZhu-apple** [comment]
r=me.

**Comment by king7532** [comment]
@YuanZhu-apple It was also a pleasure meeting you and the ResearchKit and CareKit team at dub dub! Thank you for accepting my pull request, I agree that the ResearchKit.framework `*.swift` files should support both the new Swift 3+ and existing Swift 2.x styles.  I forgot to format the Swift 2.x section of code, there are no indentations and I think that goes against the style guide.  Would you like me to fix it?

**Comment by YuanZhu-apple** [comment]
@king7532 Sure, go ahead.

**Pull request merged**
