### PR TITLE
[Umbrella headers] Update #imports to framework format

### PR DESCRIPTION
**Pull request by rsanchezsaez**
Update *umbrella header* `#import` statements to the more correct *Framework format*. Thanks to @malhal for suggesting this on [Issue #839](https://github.com/ResearchKit/ResearchKit/issues/839).

This format mirrors the rest of *Apple's iOS Framework* headers.

---

@malhal Could you confirm that a precompiled framework continues to work for you after this change?
@vtourraine Could you re-check that after the merge this branch still works through Cocoapods, and that it correctly imports the swift files?

---

This change also happily resolves the (harmless) problem explained in my second comment in [PR #648](https://github.com/ResearchKit/ResearchKit/pull/648):

> I think there's a bug in the Xcode build chain because, even though all Unit Tests build and pass fine from a clean state, an *Unable to build module ResearchKit* error appears after the tests successfully finish. On the other hand, when running the `ORKTest` app, which also uses `@import ResearchKit` (...) doesn't show this error.

It changed the problem to this (also harmless) error:

screen shot 2016-11-07 at 10 29 17 pm

But then, additionally importing the non-private *ResearchKit* module from `ORKESerialization.m` silenced it completely. (I still think there's some minor Xcode bug, as both of these errors didn't affect successful compilation and run of tests).

### CODE REVIEW

**Comment by malhal** [comment]
Hi @rsanchezsaez I can confirm this is working for my case. (That is referencing a built version of the framework from a folder other than the project folder and adding it to framework search paths.)

However when I checked out this pull request it had a build error in ORKOrderedTask.m line 1921 etc. The NSArray isn't typed so firstObject.identifier was ambiguous. I can PR a fix for this if you like.

**Comment by rsanchezsaez** [comment]
Thanks for checking!

Do you get an error or warning? What's the exact wording of it? Which version of Xcode are you running? (I'm on *Version 8.1 (8B62)*). Perhaps my Xcode version is inferring the type of the array from somewhere else?

---

Anyway, what you suggest make sense, templatized arrays are always better. Feel free to submit the PR, but let's omit the space between the type and the `<`, and also let's use `__kindof` so `ORKStep` subclasses are also valid. Like this:

     NSArray<__kindof ORKStep *> *leftSteps

Cheers!

**Comment by malhal** [comment]
Xcode Version 8.1 (8B62)

```
/Users/mh/Development/Github/ResearchKit/ResearchKit/Common/ORKOrderedTask.m:1921:96: Multiple methods named 'identifier' found with mismatched result, parameter type or attributes

/Users/mh/Development/Github/ResearchKit/ResearchKit/Common/ORKOrderedTask.m:1928:91: Multiple methods named 'identifier' found with mismatched result, parameter type or attributes

/Users/mh/Development/Github/ResearchKit/ResearchKit/Common/ORKOrderedTask.m:1929:42: Multiple methods named 'identifier' found with mismatched result, parameter type or attributes
```

**Comment by rsanchezsaez** [comment]
Weird. I guess it's *Xcode* and their caches getting funny. ¯\_(ツ)_/¯

**Comment by umerkhan-apple** [comment]
@rsanchezsaez Any updates on this one?

**Comment by rsanchezsaez** [comment]
@umerkhan-apple: Sure! I merged master and resolved the merge conflicts.

**Comment by umerkhan-apple** [comment]
Thanks @rsanchezsaez !

**Pull request merged**
