### PR TITLE
[WIP] Convert all non-English Localizable.strings to human-readable format 

### PR DESCRIPTION
**Pull request by 3lvis**
Hey guys, I started working on this task #29. It's a quite extensive one so I was wondering about something that I did first. 

**Sorting English localizations**, is that ok with you? I find localizations easy to maintain when they are structured in this way, it's easier to find where to put your localized string if you use a sorting method.

The sorting is done per section, sections that are already sorted haven't been touched.

### CODE REVIEW

**Comment by jwe-apple** [comment]
1) Would rather not reorder the English at this point, sorry. It would make it harder to track changes versus the last localization run.

2) The non-English languages should ideally be converted with an automated script rather than by hand. We have an internal process for updating these at release time, and we will need to apply the script each time the localizations go through that process. If the script has a stable sort as output, that would be preferable, since it will make for cleaner diffs.

**Comment by 3lvis** [comment]
Understood! Will see what I can do :smile:

**Comment by rsanchezsaez** [comment]
Hey @3lvis, I went ahead and implemented this ([PR#58](https://github.com/ResearchKit/ResearchKit/pull/58)). I hope you don't mind!

Best,
Ricardo

**Comment by 3lvis** [comment]
@rsanchezsaez Haha, don't worry. I see you're kicking ass!

**Comment by rsanchezsaez** [comment]
:)

**Pull request closed without merging**
