### PR TITLE
Fix localization when using  ResearchKit as Pod (Localizable.strings > ResearchKit.strings)

### PR DESCRIPTION
**Pull request by huguesbr**
Rename Localizable.strings file to ResearchKit.strings and use table name in localization, avoiding conflict when including ResearchKit as a pod (the Localizable.strings files conflict with project one)

Fix: https://github.com/ResearchKit/ResearchKit/issues/545

### CODE REVIEW

**Comment by YuanZhu-apple** [comment]
Thanks for bringing this up to us!

Overall this looks good to me.

One more change you want to include in this PR:
https://github.com/ResearchKit/ResearchKit/blame/master/CONTRIBUTING.md#L90

@rsanchezsaez Any feedback for this one?
Do you think https://github.com/ResearchKit/ResearchKit/blob/master/scripts/plist-to-strings.py need a update?

**Comment by rsanchezsaez** [comment]
This PR looks good.

Regarding `plist-to-strings.py`, I think the code is ok but the usage examples in the heading comment need to be updated from `Localizable.strings` to `ResearchKit.strings`.

Additionally, I'd take the chance to rename `ORKDefaultLocaleBundle()` to `ORKBundleForDevelopmentLocale()`.

Also, I'd move all of `ORKDefines_Private.h` contents to `ORKHelpers.h` (since most of them are not defines, and their implementations are in in `ORKHelpers.m`).

And maybe extract the `ORKDefines.h` enums to a new file called `ORKTypes.h`.

**Comment by YuanZhu-apple** [comment]
@rsanchezsaez Thanks for the review!

I agree with you to update the example code in `plist-to-strings.py`.

And maybe we can put `ORKDefines_Private.h` refactoring into a separate PR?

**Comment by huguesbr** [comment]
@YuanZhu-apple @rsanchezsaez I've made the suggested update. let me know.

**Comment by YuanZhu-apple** [comment]
@huguesbr Thanks!
This looks good to me.

**Comment by rsanchezsaez** [comment]
I think that the `ResearchKit.strings` rename removed some blank spaces from the copyright headers. How come this happened?

It's not a big deal, but maybe it's better to leave them for coherence with the rest of the files.

**Comment by umerkhan-apple** [comment]
Agree with @rsanchezsaez. Apart from minor nit, r=m3! :+1:

**Comment by huguesbr** [comment]
@rsanchezsaez @umerkhan-apple youps... fixed...

**Comment by YuanZhu-apple** [comment]
Thanks! Merging it.

**Comment by huguesbr** [comment]
thanks

**Pull request merged**
