### PR TITLE
Added property to instruction set to allow setting icon image on header view.

### PR DESCRIPTION
**Pull request by syoung-smallwisdom**
This allows an instruction step to display an icon image _above_ the title and text for the image.

simulator screen shot oct 12 2016 12 13 04 pm

### CODE REVIEW

**Comment by kelseydedoshka-apple** [comment]
This is looking great, thank you for your contribution to ResearchKit! 

Just a few minor comments:

 1. Please take a look at how the icon image looks if you supply the iconImage a really large image, like a wallpaper for example. Consider adding appropriate constrains to the icon to prevent large images from skewing the general layout of the instruction. I have attached screenshots of what I am seeing.

2. Please run the test cases and ensure any broken test cases get resolved.

This is a great addition so far, looking forward to seeing your final edits.


largeimage1
largeimage2
largeimage3

**Comment by syoung-smallwisdom** [comment]
@kelseydedoshka-apple ORKTest unit tests have been broken on master since the v1.4 convergence commit. 

https://github.com/ResearchKit/ResearchKit/commit/30742a50433cc0bd803760080033add8c7806ff3

**Comment by syoung-smallwisdom** [comment]
@kelseydedoshka-apple 
Updated to constrain the height/width of the icon image.

**Comment by rsanchezsaezsc** [comment]
@syoung-smallwisdom: I fixed `ORKTest` unit tests in [PR #862](https://github.com/ResearchKit/ResearchKit/pull/862). :-)

**Comment by rsanchezsaez** [comment]
@syoung-smallwisdom: I fixed `ORKTest` unit tests in [PR #862](https://github.com/ResearchKit/ResearchKit/pull/862). :-)

**Comment by syoung-smallwisdom** [comment]
@kelseydedoshka-apple 
Could you please take a look at pulling in #862 and I can address any issues with adding this property then.

**Comment by umerkhan-apple** [comment]
@syoung-smallwisdom We went ahead and merged PR #862. Could you pull the latest master into this PR? Thanks!

**Comment by syoung-smallwisdom** [comment]
@umerkhan-apple 
Merged master and ran serialization tests. Remaining tests are still broken on master branch and are unrelated to serialization.

**Comment by umerkhan-apple** [comment]
@syoung-smallwisdom Sounds good. This PR is not related to those tests, so we will go ahead and track that issue separately!

**Pull request merged**
