### PR TITLE
Added Dutch localization

### PR DESCRIPTION
**Pull request by BasThomas**

### CODE REVIEW

**Comment by jwe-apple** [comment]
Hi, we already have a Dutch localization! What is this patch intended to address?

**Comment by BasThomas** [comment]
It's in the more readable .strings format, which should make it easier to edit and enhace it in the future.

**Comment by jwe-apple** [comment]
Actually not a bad idea, but we should do that globally instead of a file at a time. I opened https://github.com/ResearchKit/ResearchKit/issues/29 to track. I'm going to close this particular pull request.

**Comment by johankool** [comment]
You missed LEARN_MORE_STUDY_SURVEY

**Pull request closed without merging**
