### PR TITLE
[Cocoapods] Fix podspec to include swift files

### PR DESCRIPTION
**Pull request by rsanchezsaez**
Fixes [Issue #642](https://github.com/ResearchKit/ResearchKit/issues/642).

### CODE REVIEW

**Comment by vtourraine** [comment]
Thanks for addressing this issue, but I’m afraid this won’t really solve the problem.

Once there’s a Swift file inside a Pod, projects trying to import it need to use the `use_frameworks!` Podfile option. Problem is: ResearchKit fails to build when imported by CocoaPods as a framework.

screen shot 2016-03-25 at 2 38 58 pm

So right now, including the Swift files into the ResearchKit podspec just completely breaks the CocoaPods installation method, for both Objective-C and Swift projects. Not including them, as it is today, keep it partially CocoaPods compatible, but effectively excludes some ResearchKit classes from Swift projects, as reported in #642.

And unfortunately, I don’t have a solution for this. :sos: Xcode/CocoaPods expert?

**Comment by rsanchezsaez** [comment]
Hey @vtourraine, thanks for spotting this.

I just finished an `#import` section refactor over at [PR](https://github.com/ResearchKit/ResearchKit/pull/648). I'm not completely sure, but I suspect this may fix the issue that you show on the screenshot. What is a good way to test this with a `podspec` file which is not on the main repo?

**Comment by vtourraine** [comment]
I’ve tested configuring a project using CocoaPods with your branch, and yes, compilation is now fixed. Great work! 

Looking forward to #648 being merged in.

**Comment by YuanZhu-apple** [comment]
Thanks @rsanchezsaez and @vtourraine !

**Comment by rsanchezsaez** [comment]
Careful, not sure if this truly fixes the problem without merging [#648](https://github.com/ResearchKit/ResearchKit/pull/648) (which is a pretty big refactor) as well!

**Pull request merged**
