### PR TITLE
ORKSample fixes

### PR DESCRIPTION
**Pull request by rsanchezsaez**
This PR adds the *ResearchKit* framework to `ORKSample`'s *Embed Frameworks* build phase, otherwise it won't run on devices. ~~It also, adds a custom icon for the new app~~.

### CODE REVIEW

**Comment by YuanZhu-apple** [comment]
@rsanchezsaez Thanks for the fix!
Can you make a separate PR for the new icon? It requires separate approval process, Thanks!

**Comment by rsanchezsaez** [comment]
Sure thing.

**Comment by rsanchezsaez** [comment]
Done, I have removed the icon commit from this PR. Do you want the icon's PR to be against `convergence` or `master`?

**Comment by YuanZhu-apple** [comment]
I prefer `master`.

**Comment by YuanZhu-apple** [comment]
r=me.

**Pull request merged**
