### PR TITLE
Add a single workspace that includes RK,  ORKTest, and ORKCatalog for convenience

### PR DESCRIPTION
**Pull request by YuanZhu-apple**
Save developer's effort in switching between project files.

### CODE REVIEW

**Comment by YuanZhu-apple** [comment]
@rsanchezsaez What do you think?

**Comment by rsanchezsaez** [comment]
This is very convenient indeed. I was constantly opening and closing `ORKCatalog` and `ORKTest` before. ;-)

I wonder if we should remove the `ResearchKit` subproject from the individual `ORKCatalog` and `ORKTest` projects. But maybe not, because it doesn't seem to have any ill effects, and that way those can still be opened individually without using the *workspace*.

All targets and tests work ok when run from the workspace.

**Comment by YuanZhu-apple** [comment]
Cool!

**Comment by rsanchezsaez** [comment]
@YuanZhu-apple: A small nit I missed: wouldn't `ResearchKit.xcworkspace` be a better name than `RKWorkspace.xcworkspace`? Adding *filetype information* to a file name doesn't feel right.

**Comment by umerkhan-apple** [comment]
@rsanchezsaez I think RKWorkspace is a bit more definitive, since the `ResearchKit` title is used for the framework already. We do not require the entire workspace to be included in order to use ResearchKit, so this helps differentiate between the workspace and the actual framework.

**Comment by rsanchezsaez** [comment]
@umerkhan-apple That makes sense.

I was also thinking about a names like `RKSamples` instead of  `RKWorkspace`, but it's not ideal either because `ORKCatalog` is a sample, but `ORKTest` is more of a manual test suite.

**Pull request merged**
