### PR TITLE
Fixes #992. "Consent PDF with htmlReviewContent doesn't add signature page

### LINKED ISSUE #992: Consent PDF with htmlReviewContent doesn't add signature page
If an ORKConsentDocument is initialized with separate review content as HTML in its htmlReviewContent property, then the signature page is not added to the end of the PDF produced by "ORKConsentDocument makePDFWithCompletionHandler".

I believe this is due to:

ORKConsentDocument.m lines 196-204 which are never reached if the ConsentDocument is using _htmlReviewContent (rather than concatenating ORKConsentSections) . I believe this could be fixed by moving lines 196-204 out of the else block so that they are always reached, whether sections are being concatenated on htmlReviewContent is being used.

from ORKConsentDocument.m:

```
- (NSString *)htmlForMobile:(BOOL)mobile withTitle:(NSString *)title detail:(NSString *)detail {
    NSMutableString *body = [NSMutableString new];
    
    ...

    if (_htmlReviewContent) {
        [body appendString:_htmlReviewContent];
    } else {
        
        ...

       // tahoupt: lines 194-206 not reached if _htmReviewContent!
        if (!mobile) {
            // page break
            [body appendFormat:@"<h4 class=\"pagebreak\">%@</h4>", _signaturePageTitle ? : @""];
            [body appendFormat:@"<p>%@</p>", _signaturePageContent ? : @""];
            
            for (ORKConsentSignature *signature in self.signatures) {
                [body appendFormat:@"%@", [_signatureFormatter HTMLForSignature:signature]];
            }
        }
    }
    
    return [[self class] wrapHTMLBody:body mobile:mobile];
}
```

### PR DESCRIPTION
**Pull request by mirlhaq**
Fixes #992. "Consent PDF with htmlReviewContent doesn't add signature page.

The original (unresolved and closed by lack of activity) issue is #992 .
I checked the issue and also this change works.

### CODE REVIEW

**Comment by kelseydedoshka-apple** [comment]
@mirlhaq - thanks for the fix here, been an issue many others have encountered so really appreciate the fix to this!

**Comment by rsanchezsaez** [comment]
This PR broke the `ResearchKit` unit tests.

**Comment by rsanchezsaez** [comment]
```
(lldb) po self.mockWriter.html
<html><head><style>@media print { .pagebreak { page-break-before: always; } }
h1, h2 { text-align: center; }
h2, h3 { margin-top: 3em; }
body, p, h1, h2, h3 { font-family: Helvetica; }
.col-1-3 { width: 33.3%; float: left; padding-right: 20px; }
.sigbox { position: relative; height: 100px; max-height:100px; display: inline-block; bottom: 10px }
.inbox { position: relative; top: 100%%; transform: translateY(-100%%); -webkit-transform: translateY(-100%%);  }
.grid:after { content: ""; display: table; clear: both; }
.border { -webkit-box-sizing: border-box; box-sizing: border-box; }
</style></head><body><div class='header'></div>some content<h4 class="pagebreak"></h4><p></p></body></html>

(lldb) po [self htmlWithContent:@"some content"]
<html><head><style>@media print { .pagebreak { page-break-before: always; } }
h1, h2 { text-align: center; }
h2, h3 { margin-top: 3em; }
body, p, h1, h2, h3 { font-family: Helvetica; }
.col-1-3 { width: 33.3%; float: left; padding-right: 20px; }
.sigbox { position: relative; height: 100px; max-height:100px; display: inline-block; bottom: 10px }
.inbox { position: relative; top: 100%%; transform: translateY(-100%%); -webkit-transform: translateY(-100%%);  }
.grid:after { content: ""; display: table; clear: both; }
.border { -webkit-box-sizing: border-box; box-sizing: border-box; }
</style></head><body><div class='header'></div>some content</body></html>
```

**Comment by windenchanter** [comment]
I think to add signature you need to append contents inside this if statement. 
This worked for me. But I am a new user and non-programmer, so I haven't figured out how to commit contents yet...  just in case this can help others to get this function to work. 
```
if (_htmlReviewContent) {
         [body appendString:_htmlReviewContent];
     } 
```

insert this

```
        if (!mobile) {
            // page break
            [body appendFormat:@"<h4 class=\"pagebreak\">%@</h4>", _signaturePageTitle ? : @""];
            [body appendFormat:@"<p>%@</p>", _signaturePageContent ? : @""];
            
            for (ORKConsentSignature *signature in self.signatures) {
                [body appendFormat:@"%@", [_signatureFormatter HTMLForSignature:signature]];
            }
```

**Pull request merged**
