### PR TITLE
Replaced magic numbers in OKHTMLPDFWriter.m

### PR DESCRIPTION
**Pull request by franklinsch**

### CODE REVIEW

**Comment by jwe-apple** [comment]
Good idea, but use static const instead for type safety.

**Comment by franklinsch** [comment]
Good idea. I updated the file

**Comment by jwe-apple** [comment]
Sorry to be a stickler, but these are passed to CGSize so should be CGFloat (different behavior 64 vs 32-bit)

**Comment by franklinsch** [comment]
Woops, sorry about that! Updated.

**Comment by jwe-apple** [comment]
Thanks!

**Pull request merged**
